server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/blog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    minEvictableIdleTimeMillis: 30000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
web:
  host:
    url: http://127.0.0.1:8080
    white: http://127.0.0.1:8080,http://127.0.0.1:8888
    app:
      url: http://127.0.0.1:8888
    file:
      url: